### ISSUE TITLE
Conceptual Design for User Interfaces used in Knit Web App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#14]
Please define the following for your project
a) Feature List
b) Project Plan with possible Milestones (Which features will be implemented at what time)

> Plan and develop the web front end and pattern editor. Start with creating compelling and convincing mockups in awesome design. Develop it with Python and possibly use Flask as a framework or suggest another solution. https://github.com/fashiontec/knitapps/issues/12

**Comment by sameeragunarathne** [comment]
a) Project Feature List for Web Front end and Pattern Editor

1. User is given a account and user have to log on to the account to start a knitting process.
2. Knitting works are stored as projects so that user will be able to save and load them for later editing.
3. User is given a workspace to work on the patterns and configuration. workspace consists of pattern editor and knitting simulator.
4. There are default pattern types are given with each project or user can download or upload patterns to the workspace.  

Feature list for Pattern Editor

1. Patterns can be loaded to projects as in various formats including jpg, png and gif.
2. Each pattern is pixelated to present how the stitches are going to apply to the pattern.
3. User will be able to adjust a single cell size manually and the grid will be formulate on top of entire image according to that cell size
4. User will be able to edit the pattern by adding operations to the whole pattern (brightness, contrasting, rotating, inverting, repeating etc).
5. User will be able to edit the pattern by adding operations to a single cell or a region of cells (draw, change color, fill region etc).
6. After the editing is done the pattern is auto saved and prompted to the next steps in knitting process.

NOTE:User is allowed to do those operations according to the maximum pattern size allowed by the machine. Otherwise user will be notified by the application.

Feature list for Knitting Simulator

1. In this window user wants to configure knitting details like needle position, color details etc in the configuration panel . For the current implementation 2-4 colour schema is applied to the pattern.
2. After configuration user can load the program to the arduino by clicking Start Knitting. Knitting simulator is there to give simulation of the knitting process to the user.
3. A graphical simulation of the pattern and a log including progress details are provided to the user.

**Comment by sameeragunarathne** [comment]
Conceptual Design for User Interfaces used in Knit Web App

Design for Home Page
![screenshot from 2015-05-22 17 49 59](https://cloud.githubusercontent.com/assets/5234677/7783627/c7d308b4-0165-11e5-8f81-f9186f7e60a1.png)
This is the page where user gets soon after log in to the application. In this design user can keep track of the knitting work by managing them as seperate projects. User can choose a previously worked knitting project or a new one from here. 

Design for Pattern Editor
![screenshot from 2015-05-22 17 08 48](https://cloud.githubusercontent.com/assets/5234677/7783630/dc50092c-0165-11e5-8be5-d6a63ae40f17.png)
After entering to a project user will be redirected to the workspace of the project. workspace consists of two major components. They are pattern editor and knitting simulator. In pattern editor user can load the pattern file as a image format and editor will pixelate the image according to user defined pixel dimensions. So that pattern will be easily editable according to the rows and stitches allowed for knitting. Editor provides tools for edit each cell on the grid formulated. User will be able to edit using allowed RGB value ranges for each cell. Further more the functionalities like turn, flip, replicating(repeating) are intended to add to the pattern editor.

Design for Knitting Simulator
![screenshot from 2015-05-22 17 39 30](https://cloud.githubusercontent.com/assets/5234677/7783631/eb8a57c6-0165-11e5-9299-392e54a0a772.png)
This component of the workspace allows user to configure knitting details like needle position, color details etc and then start the knitting process . Knitting simulator is there to give simulation of the knitting process to the user. In this knitting progress details are shown to the user both graphically and as a log.

**Comment by tian2992** [comment]
I think the design is overall fine, however try to simplify the scope. Why do we need a menu bar in workspace? Think the task of each specific environment and what is going to be done in each. For example: Workspace will be used on the 'knitting' step, meaning it will have to display a progress bar, a start and stop button, etc. Do we need projects? How can we save and load projects? etc.

Cheers!

**Comment by sameeragunarathne** [comment]
@tian2992 Thanks for the comment. My initial purpose on the features that focuses in your comment is as follows.
             Menu bar is there to load the image patterns and provide basic operations on the pattern such as loading a image, saving the file, giving pattern size etc. After doing necessary editing to the pattern user can proceed to the next window (by clicking proceed to knitting button) which user will be displayed available port details, colors, needle position, machine type etc and user will be able to configure them at there. After configuration, user should press start knitting button to load the program to arduino and run the process. Knitting progress bar is shown in the simulator area with the graphical simulation of the pattern (simulation of which row and stitch currently machine is at). 
             Using of projects is to keep track of some user's work. I intended to have a cloud mysql database to keep user details and their project details. So that we are able to keep track of the user projects and allow them to save and work later on the projects. If this is unnecessary feature it can be remove from the feature list. Please give your ideas. Thank You.

**Comment by mariobehling** [comment]
Please also add info for milestones and technologies used to your plan.
Dates for Milestones
    Milestone 1, Due by June 10, 2015
    Milestone 2, Due by June 26, 2015
    Milestone 3, Due by July 25, 2015
    Milestone 4, Due by August 21, 2015
