### ISSUE TITLE
Only show tweets and retweets of @fossasia

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#174]
Currently tweets that are not coming from The Twitter "FOSSASIA" are showing up. We only want to show tweets coming from the twitter twitter.com/fossasia showing up.

**Comment by simsausaurabh** [comment]
@mariobehling please clarify are you referring to the fossasia/loklak_search for showing tweets from @foasasia ?

**Comment by mariobehling** [comment]
We are trying for more than a year now to get the tweets of twitter.com/fossasia there, but something always is not right even though it looks sometimes that it is finally fixed. Problems were that either only tweets are shown and not the retweets or that all kinds of tweets of others are shown etc. Currently it shows different tweets, but it should only show the tweets of @fossasia.

Check here
![screenshot from 2018-01-18 12-51-35](https://user-images.githubusercontent.com/1583873/35096951-5970000c-fc4e-11e7-861f-b9caddd3deb5.png)

**Comment by simsausaurabh** [comment]
@mariobehling I have started to explore for the solution of this problem and process it as soon as possible.

**Comment by simsausaurabh** [comment]
@mariobehling  I have been working on this problem and according to the requirement I changed js/tweetsfetcher.js and index.html tag which is querying for data-query="fossasia" to take data-query="from:fossasia" and its working for other query e.g. "from:mariobehling" and "from:singhpratyush_". I also made it show tweets from both of these twitter accounts by "from:mariobehling OR from:singhpratyush_" and its giving the results but the problem is that we can't show the tweets which are older than 30 days. And I think loklak API is not made for returning the retweets. So either we would have to make changes in that or, still I am searching for the solution because there is a chance that we can get those tweets by having a check on the start and end date to the range tweets has to be taken. I am attaching outputs of those searches I have made. Fossasia's tweets are not showing because the tweets are older than 30 days and remaining are the retweets.

**Comment by simsausaurabh** [comment]
But there is also a choice if we want to take tweets and retweets directly from twitter account of '@fossasia'
without using loklak API, but still I am looking for the solution of above. Please suggest any remark. @mariobehling

**Comment by simsausaurabh** [comment]
![screenshot from 2018-01-19 23-55-40](https://user-images.githubusercontent.com/16608864/35165497-80c622cc-fd74-11e7-93ba-cc04235bbb98.png)
![screenshot from 2018-01-19 23-56-05](https://user-images.githubusercontent.com/16608864/35165502-82071650-fd74-11e7-9936-2b3215bd4ba4.png)

**Comment by simsausaurabh** [comment]
The link given below is the API call of loklak search used in the website. I have made it to extract the tweets from only sagarcasm(example). Please review this link:
https://api.loklak.org/api/search.json?callback=loklakFetcher.handleData&q=from:sagarcasm

**Comment by mariobehling** [comment]
Seems like the way to go. Could you make a PR and provide a preview link for the 2018 website, please?

**Comment by simsausaurabh** [comment]
Yeah sure, for only 'from:fossasia' right ? 
shall I also add yours tweeter-account tweets along with the fossasia ?

**Comment by ShubhangiMisra** [comment]
Hey @mariobehling is the issue reloved? @simsausaurabh  are you still working on it. If anyone does not mind, can I this up?
Thanks!

**Comment by mariobehling** [comment]
Tweets stopped working after this merge.

**Comment by simsausaurabh** [comment]
@mariobehling As mentioned in #523, ```api.loklak.org``` is no longer fetching tweets that are only from ```fossasia```(It is due to the less no of tweets- only from fossasia). It is returning tweets from all the places in which ```fossasia``` is mentioned. So for the time being either new tweets has to be made from fossasia, or shall we make it again like before, which will fetch tweets from all places mentioning ```fossasia```.
