### ISSUE TITLE
responsiveness issue on hover over an image

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/2018.fossasia.org#39]
it seems not good that background exceed the width of image when user hover on an image,

![image](https://user-images.githubusercontent.com/25322851/30237775-8f655fea-9556-11e7-9408-192a3d593db7.png)

**Comment by AshishkrGoyal** [comment]
@mariobehling sir
can i work on it?

**Comment by niccokunzmann** [comment]
@AshishkrGoyal In general, you can work on it without permission. Usually the permission is granted in the LICENSE file which is missing here. In order to not do work another person also does, share your work status as soon as possible in the issue. So, yes, you can work on it. Please always let other people know what you are doing. There is no "this code/problem belongs only to me" in open-source. :)

**Comment by AshishkrGoyal** [comment]
@niccokunzmann 
Thanks Sir

**Comment by sagar-kalra** [comment]
There is no issue like this, i checked it on firefox and chrome both.
