### ISSUE TITLE
Add Speakers- Neha Kumari, Joyce Ng

### ISSUE THREAD

**Issue by gautamjajoo** [fossasia/2018.fossasia.org#398]
### Add the following Speakers  

1. Neha Kumari,
2.  Joyce Ng.

### Do you want to work?

Yes

@hpdang @edenyay

**Comment by iknoorjobs** [comment]
@gautamjajoo Can I work on this?

**Comment by gautamjajoo** [comment]
@iknoorjobs You can,  once approved by the mentors.

**Comment by edenyay** [comment]
hi @gautamjajoo please se my status update:

1. Neha Kumari, please add and use this photo
![img_20170601_191525](https://user-images.githubusercontent.com/32028823/35732003-6714264a-084a-11e8-9afa-ad2b3f70a992.jpg)

2. Joyce Ng, please add her and use this photo
![joyce_picture](https://user-images.githubusercontent.com/32028823/35731475-414a2aec-0848-11e8-8c09-7e7cdd3067f6.png)

3. Keerthana S, not yet confirmed
4. Venkatesh Duggirala, already added
5. Aniketh Girish, not yet confirmed

3. Team Ethical Hacking, please add and use this photo
![p1013965ima](https://user-images.githubusercontent.com/32028823/35731599-d2cac71a-0848-11e8-9127-d7819a768de2.jpg)

Please update the issue with the names of the speakers you are going to add, so that I can follow up with the rest of missing speakers. Thank you!

**Comment by gautamjajoo** [comment]
@edenyay Team Ethical Hacking is to be added in the Team Section?

**Comment by edenyay** [comment]
@gautamjajoo no, in the speaker session, count as 1 speaker

**Comment by gautamjajoo** [comment]
@edenyay The job title of Venkatesh Duggirala is coming in two lines which is causing problem for adding other speakers. Can we make it short? NO speaker could be added below that row.

**Comment by edenyay** [comment]
@gautamjajoo let's change that into **Senior Principal Technical Staff**
